server:
  port: 2000
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 118.24.38.46:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: false