nacos:
  config:
    bootstrap:
      enable: true
      # 主配置服务器地址
    server-addr: 118.24.38.46:8848
    # 主配置 data-id
    data-ids: sms
    # 主配置 group-id
    group: DEVELOP
    # 主配置 配置文件类型
    type: yaml
    # 主配置 开启自动刷新
    auto-refresh: true
    # 主配置 最大重试次数
    max-retry: 10
    # 主配置 重试时间
    config-retry-time: 2333
    # 主配置 配置监听长轮询超时时间
    config-long-poll-timeout: 46000
    # 主配置 开启注册监听器预加载配置服务（除非特殊业务需求，否则不推荐打开该参数）
    enable-remote-sync-config: true
logging:
  level:
    com:
      gapache:
        sms:
          server: debug