server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
#      routes:
#        - id: payment_routh # 没有固定规则，要求唯一
#          uri: lb://cloud-payment-service
#          predicates:
#            - Path=/api/payment/**
#        - id: payment_routh2 # 没有固定规则，要求唯一
#          uri: lb://cloud-payment-service
#          predicates:
#            - Path=/api/payment/**

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/