server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
#          这个分组对持久化非常重要
#          group: study

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    #    主机名修改
    instance-id: cloud-stream-provider
    #    访问路径可以显示ip地址
    prefer-ip-address: true