server:
  port: 7001
spring:
  application:
    name: oms-pull-order-server
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        output:
          destination: orderExchange
          content-type: application/json
logging:
  level:
    com.gapache.oms.pull.order.server.message.impl: debug