spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200,http://localhost:9201
  redis:
    host: 118.24.38.46
    database: 3
    password: 521428Slyt
server:
  port: 8090
dubbo:
  application:
    name: blog-server
  registry:
    address: zookeeper://118.24.38.46:2181