server:
  port: 7002
spring:
  application:
    name: oms-split-order-server
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
  cloud:
    nacos:
      discovery:
        server-addr: 118.24.38.46:8848
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        input:
          destination: orderExchange
          content-type: application/json
          group: sichuan
  redis:
    host: 118.24.38.46
    port: 6379
    password: 521428Slyt
logging:
  level:
    com.gapache.oms.split.order.server.message: debug
    com.gapache.oms.split.order.server.service: debug
    com.gapache.oms.store.location.sdk.feign: debug

