server:
  port: 8008
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
#  设置feign客户端超时时间（OpenFeign默认支持ribbon）
#ribbon:
#  指的是建立连接后从服务器读取到可用资源所用的时间 默认1秒
#  ReadTimeout: 5000
#  指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ConnectTimeout: 5000
logging:
  level:
#    feign日志以什么级别监控哪个接口
    com.gapache.cloud.order.feign.PaymentFeign: debug
feign:
  hystrix:
    enabled: true