dubbo:
  application:
    name: blog-admin
    qos-port: 22224
  registry:
    address: nacos://118.24.38.46:8848
    timeout: 5000
  provider:
    timeout: 5000
  consumer:
    timeout: 5000
server:
  port: 8091
  servlet:
    context-path: /blog-admin