server:
  port: 2002
spring:
  application:
    name: seata-storage-service
  datasource:
    url: jdbc:mysql://118.24.38.46:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 521428Slyt!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
  cloud:
    nacos:
      discovery:
        server-addr: 118.24.38.46:8848
    alibaba:
      seata:
        tx-service-group: save

management:
  endpoints:
    web:
      exposure:
        include: '*'

#  设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #  指的是建立连接后从服务器读取到可用资源所用的时间 默认1秒
  ReadTimeout: 5000
  #  指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true