server:
  port: 10003
spring:
  application:
    name: blog-server
  cloud:
    nacos:
      discovery:
        server-addr: 118.24.38.46:8848
  elasticsearch:
    rest:
      uris: http://localhost:9200
  redis:
    host: 118.24.38.46
    database: 3
    password: 521428Slyt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.38.46:3306/blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 521428Slyt!
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
feign:
  hystrix:
    enabled: false
gapache:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI4FwKoMqrMCTzsBARyiaK
    access-key-secret: A6pCD5Jz5vhxilpWOLJnCXv59Cmt0K
