server:
  port: 7001
eureka:
  instance:
#    eureka服务端的实例名称
    hostname: eureka7001
  client:
#    不用向注册中心注册自己
    register-with-eureka: false
#    不需要去检索服务
    fetch-registry: false
#    设置于Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7002:7002/eureka/
#  server:
#    关闭自我保护机制，保证不可用服务被及时剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: eureka-server7001