server:
  port: 8002
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
#    主机名修改
    instance-id: order8002
#    访问路径可以显示ip地址
    prefer-ip-address: true
#    Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2